### ISSUE TITLE
Username/password

### ISSUE THREAD

**Issue by pa1er** [H4nsie/EnphaseEnvoy#2]
Hej H4nsie, 

Tool looks fine. I am using domoticz for a while and now also have some solar panels with an Envoy-s metered. I would like to use youre plugin but the software version is 7. Can you telle me where I can found the needed username/password?

br/ 
Erik-Jan

**Comment by H4nsie** [comment]
Hoi Erik-Jan,

It's your Enphase password. The plugin uses it for obtaining the access token from Enphase (that's new in V7). You can test your password at https://entrez.enphaseenergy.com/

Note: plugin is not tested with the 'metered' version of the Envoy. 

Regards, Hans

**Comment by pa1er** [comment]
Hej Hans, 
I still have some problems with my access but that has to do with the registration of the solar company.
As soon as i know more I will let you know.

br/
Erik-Jan

**Comment by pa1er** [comment]
IT WORKS,

With the right cridentials I can inform you that this plugin is working perfect with 11 solar panels connected to an  Envoy-s metered. 

Thanks a lot!
Erik-Jan
