### ISSUE TITLE
Version shows undefined

### ISSUE THREAD

**Issue by 0crap** [H4nsie/EnphaseEnvoy#4]
I think since updating to Domoticz 2023.1 the Version of my Envoy gateway is not shown anymore.
If you go to Setup -> Hardware -> Enphase Envoy - with micro inverters

![2023-1](https://user-images.githubusercontent.com/31951195/221795760-97d7b814-3249-4d6b-949d-fbdde42a31ae.png)

![Undef](https://user-images.githubusercontent.com/31951195/221795782-22a9f617-fbfa-4b8d-825d-a916beb00860.png)

The version on the Envoy is still the same, D7.0.88
Not a big deal, but I think this worked before.

**Comment by H4nsie** [comment]
Version number is correctly defined in code. Seems Domoticz issue since 2023.1
All my domotica hardware has 'Version: undefined' since upgrading to 2023.1

**Comment by 0crap** [comment]
Fair.
Since more of your hardware seems to behave the same, it will probably be solved on the Domoticz side of it.

However I do notice the native Enphase implementation seems to be able to get it right.

![Version](https://user-images.githubusercontent.com/31951195/222722443-e555192d-88e1-4ae6-8d62-0b0fbd659066.png)

**Comment by 0crap** [comment]
Switched to Domoticz native implementation.
