### ISSUE TITLE
Comparison script vs native

### ISSUE THREAD

**Issue by 0crap** [H4nsie/EnphaseEnvoy#5]
Domoticz 2023.1 now has a native Envoy D7 implementation.
For the fun of it I compared it with my current setup using the script from H4nsie.
**Conclusion for now, I like the script better!** 👍 

I noticed a few things which might also be considered to improve the script.
First a screenshot of the native implementation.
![Native_1](https://user-images.githubusercontent.com/31951195/221798903-14dddf12-fb0e-4a16-b838-67b4ab46dc45.png)

As you can see there is a pull down menu for the polling interval.
![Poll interval](https://user-images.githubusercontent.com/31951195/221799158-4d17aa1e-0547-4b83-a061-6f71d5f857e2.png)

This might be something to implement for the script as well.
The H4nsie script is currently polling the inverters every 50 seconds.
Personally I find that to be perfectly fine, but others might like to have a choice.

The polling interval, on the native implementation, also goes for the total Production counter.
However the current H4nsie script is updating the total Production counter only every 5 minutes.

~~It would be nice to change the total Production counter, from the H4nsie script, to match it to the inverter polling time of 50 seconds IMHO.~~ Forget this, it seems the Envoy itself only updates around 5 minutes anyway.

I also noticed the native implementation uses for the total Production counter a General - kWh Type/Subtype.
While the H4nsie script uses a P1 Smart Meter - Energy Type/Subtype.
It might be personal preference, but I like the P1 Smart Meter better. 💯 

Just some food for thought. Thx.

**Comment by 0crap** [comment]
Well, I think I can answer my own question.
I have set the polling interval to 20 seconds on the native implementation.
Funny thing is that the Total counter as well as the inverters are only showing new values around every 5 minutes.

So the Poll Interval drop down box makes no sense a the moment. (Does not give quicker new values from the hardware.)
Unless Enphase gives the D7 firmware a near real-time update option we can leave it as it is for now.

Hope this helps if anyone finds this post using Google and looking for answers on this topic. :-)

**Comment by H4nsie** [comment]
Hi! It *should* be possible to update more frequent. 

In D7 the command "/installer/pcu_comm_check" is supported and forces the inverters to respond their values. That can be done every minute. #on_my_todo_list

My Envoy is still at D5 (asked for update but have to wait, they said.). The native Domoticz Envoy implementation does not support D5 anymore since last update... so that's broken for me.

**Comment by 0crap** [comment]
Thx for your reply!

I think it's not needed to update more often, but people like choices. :-)
Always nice if you can add it at some point.
Crazy you're still on D5. That for sure does not help development...
Nothing you can do about atm. ¯\_(ツ)_/¯

**Comment by 0crap** [comment]
I wish I could extract the inverter voltage and temp values to log in Domoticz.
But that is something else...
