### ISSUE TITLE
Sometimes zero/wrong readings on the Total Production counter

### ISSUE THREAD

**Issue by 0crap** [H4nsie/EnphaseEnvoy#6]
With the current script version I do notice some spikes that go to zero on the "Usage Last 3 Days - total counter".
![Zero readings](https://user-images.githubusercontent.com/31951195/221824435-239176c6-5af9-4c99-957f-edcfed8df62a.png)
This must be a false recording, because it's not suddenly dark mid day and the output is 0 Watt.
Also these spikes that go to zero are not seen on any of the Inverters - Generated Last 3 Days graphs themselves.

The total counter - Usage Last Week bar graphs seem to match with the daily recorded kWh as seen in the Enlighten App.
So it seems the spikes that go to zero are only a graphical mismatch and not effecting the daily recorded kWh's.

Anyone else seeing this behavior?

**Comment by 0crap** [comment]
It's not only zero readings, but also simply wrong readings on the Total Production counter.
Yesterday is a good example, all day a blue sky and little activity at home that day.

First a screenshot of the Total Production counter:
![Envoy-total](https://user-images.githubusercontent.com/31951195/222725376-7d7f03f7-00bc-4936-9d45-c260e5205d7c.png)
A lot of irregularities shown (not a smooth curve) and a peak production value which is definitely not possible.
The Enhase App shows the correct peak value:
![App](https://user-images.githubusercontent.com/31951195/222725730-90e2c7e9-f505-4866-8ee2-cdd358916e2f.png)

Lastly the P1 measurement by Domoticz, which shows the return values. (Electricity "Smart meter" values.)
Much more smooth curve is shown here:
![P1 results](https://user-images.githubusercontent.com/31951195/222725946-f040fce6-0fe6-4e2d-bdcd-72dd98003ce9.png)

So IMHO there seems something wrong with the script logic that creates the Envoy-S - total graph.
Anything that can be done to improve this?
Anyone that uses the script from H4nsie that is willing to add there Envoy-S total graph?
I would love to have some comparison to see if I'm not the only one seeing this.
Thx!

**Comment by H4nsie** [comment]
Could be a temporarly lost connection to the Envoy? It is known when one poll does not read, it is added to the next poll. That could explain the high readings. 

The total production counter (kWh / day) is kept by the Envoy and read every time. So that value should always be correct.

**Comment by 0crap** [comment]
> Could be a temporarly lost connection to the Envoy? It is known when one poll does not read, it is added to the next poll. That could explain the high readings.
> 
> The total production counter (kWh / day) is kept by the Envoy and read every time. So that value should always be correct.

Sporadically, two times a week or so at a random day, I've noticed a temporary connection lost to the Envoy.
Edit: `2023-03-16 23:01:07.884 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly`
So that is not the case.

It seems very true that a missing value is added to the next one.
That gives crazy spikes, especially mid day when the values are simply higher numbers.
I'm not sure what the root cause is.
For sure not nice this happens, next to being a messy graph, also peak power delivery (and possible clipping) can not be checked.

When it happens it seems a better idea to just ignore it and not add it to the next sample.
Especially, like you say, the total production counter will always be correct.
Best is to get it fixed and the graph looks like the individual panels. (Which do not suffer from this issue.)

![Panel](https://user-images.githubusercontent.com/31951195/225428873-2d5732b2-d1a4-403c-8abe-2326693691bb.png)

**Comment by H4nsie** [comment]
To increase the polling frequency, you could change the value 2 to a value of 1 on line 50:

self.freq = 2 #multiplier for Domoticz.Heartbeat (no need to update frequent as Envoy itself is updated only every 5 minutes.)

**Comment by 0crap** [comment]
> To increase the polling frequency, you could change the value 2 to a value of 1 on line 50:
> 
> self.freq = 2 #multiplier for Domoticz.Heartbeat (no need to update frequent as Envoy itself is updated only every 5 minutes.)

Done, let's see if that improves things a bit...
I'll report back.

**Comment by 0crap** [comment]
Finally some sun to see how it goes.
Unfortunately setting `self.freq = 1` does not help.

As you can see, the total counter is not a nice flat line as it should be, including a mistake which gives crazy offset.
The panels give a graph that reflects the reality perfectly. (I had some clipping, so flat line from the panel is correct.)
I hope the total counter can be fixed.

![2-4_total](https://user-images.githubusercontent.com/31951195/229362554-435da004-82e7-4264-a696-1bdd19c3e00d.png)
![2-4_panel](https://user-images.githubusercontent.com/31951195/229362566-0366653c-8b4e-47d5-b129-bec0e0348f7e.png)

**Comment by 0crap** [comment]
Any update on this one? Issue is still there.
If I change to `self.freq = 4` the problem gets even worse.

For testing purposes, can we change the Total counter from a Type: `P1 Smart Meter` to a Type: `General, kWh`??
Happy to test if that gives better results.
Thx.

**Comment by 0crap** [comment]
Switched to Domoticz native implementation.

**Comment by H4nsie** [comment]
> Switched to Domoticz native implementation.

I would like too, but my Envoy is still on V5 and Domoticz native does not support V5 anymore...

**Comment by H4nsie** [comment]
See same kind of problems at HA implementation. [https://gathering.tweakers.net/forum/list_message/75503342#75503342](url)

**Comment by H4nsie** [comment]
My Envoy is updated to v7 and is supported by Domoticz's native implementation. Not maintaining this source anymore.
